name: Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write  # Needed for deployment-token

jobs:
  test-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests on ${{ matrix.browser }} browser
        run: |
          pytest ./tests --browsers=${{ matrix.browser }} --alluredir=./allure-results -n=auto --headless

  report-builder:
    runs-on: ubuntu-latest
    needs: test-execution
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch gh-pages branch to a separate directory
          fetch-depth: 0

      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages

      - name: Check out gh-pages branch
        run: |
          git checkout gh-pages

      - name: Build and deploy Allure report
        run: |
          mkdir -p allure-history
          mv allure-results allure-history/
          
          allure generate allure-history --clean -o allure-report
          
          mv allure-report/* ./
          
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()

  pages-deploy:
    runs-on: ubuntu-latest
    needs: report-builder
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
