name: Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  test-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests on ${{ matrix.browser }} browser
      run: |
        pytest ./tests --browsers=${{ matrix.browser }} --alluredir=./allure-results -n=auto --headless

    - name: Upload completion signal
      run: echo "${{ matrix.browser }} completed" > completion-${{ matrix.browser }}.txt
      if: always()
      continue-on-error: true

    - name: Upload completion artifact
      uses: actions/upload-artifact@v3
      with:
        name: completion-${{ matrix.browser }}
        path: completion-${{ matrix.browser }}.txt

    - name: Download all completion artifacts
      uses: actions/download-artifact@v3
      with:
        name: completion-chrome
        path: ./completion/
      if: ${{ matrix.browser == 'chrome' }}

    - name: Download all completion artifacts
      uses: actions/download-artifact@v3
      with:
        name: completion-firefox
        path: ./completion/
      if: ${{ matrix.browser == 'firefox' }}

    - name: Download all completion artifacts
      uses: actions/download-artifact@v3
      with:
        name: completion-edge
        path: ./completion/
      if: ${{ matrix.browser == 'edge' }}

    - name: Wait for all tests to complete
      run: |
        while [ $(ls ./completion | wc -l) -lt 3 ]; do
          echo "Waiting for all tests to complete..."
          sleep 10
        done

    - name: Load test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
