name: Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
  pages: write

jobs:
  test-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests on ${{ matrix.browser }} browser
      run: |
        pytest ./tests --browsers=${{ matrix.browser }} --alluredir=./allure-results -n=auto --headless

  report-builder:
    runs-on: ubuntu-latest
    needs: test-execution
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch gh-pages branch
      run: |
        git fetch origin gh-pages:gh-pages

    - name: Load test report history
      run: |
        git checkout gh-pages
        mkdir -p gh-pages

    - name: Merge remote changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git pull origin gh-pages --rebase || git rebase --abort

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results

    - name: Commit and push changes
      run: |
        git add -A
        git commit -m "Update Allure report"
        git push origin gh-pages --force
      if: always()

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./allure-report

