name: Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  test-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests on ${{ matrix.browser }} browser
      run: |
        pytest ./tests --browsers=${{ matrix.browser }} --alluredir=./allure-results -n=auto --headless

    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results-${{ matrix.browser }}
        path: ./allure-results

  report-builder:
    runs-on: ubuntu-latest
    needs: test-execution

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Download all Allure test adresults
      run: |
        for browser in chrome firefox edge; do
          mkdir -p ./allure-results/$browser
          gh-action-download-artifact -n allure-results-$browser -p ./allure-results/$browser
        done

    - name: Merge Allure results
      run: |
        mkdir -p ./allure-results-merged
        cp -r ./allure-results/*/* ./allure-results-merged/

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results-merged

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
